namespace TagEkyc.Infrastructure.CaptureRuntime;

// Closed A1 startup catalogue; no target-dependent readiness selector.
internal static class CaptureRuntimeStartupCatalogue
{
    internal static readonly string[] Tables =
    [
        "platform_operator_credentials",
        "capture_runtime_role_policy_revisions",
        "capture_runtime_role_policy_heads",
        "capture_runtime_trust_profile_revisions",
        "capture_runtime_trust_profile_heads",
        "capture_runtime_configuration_revisions",
        "capture_runtime_configuration_heads",
        "capture_runtime_registrations",
        "capture_runtime_installations",
        "capture_runtime_credential_generations",
        "capture_runtime_request_nonces",
        "capture_runtime_bootstrap_issuances",
        "capture_capabilities",
        "capture_execution_bindings",
        "capture_runtime_configuration_overrides",
        "capture_runtime_rotation_authorizations",
        "capture_runtime_management_operations",
        "capture_runtime_management_events",
        "capture_capability_operations",
        "capture_capability_events",
        "capture_runtime_bootstrap_redemption_operations",
        "capture_runtime_rotation_completion_operations",
        "capture_runtime_bootstrap_redemption_events",
        "capture_runtime_rotation_completion_events",
        "platform_operator_root_operations",
        "platform_operator_root_events",
        "capture_runtime_cutover_state",
    ];
    internal static readonly string[] Functions =
    [
        "tagekyc.c6ba_roles_are_canonical(text[])",
        "tagekyc.c6ba_reject_row_mutation()",
        "tagekyc.c6ba_validate_current_generation()",
        "tagekyc.c6ba_validate_capability_graph()",
        "tagekyc.c6ba_validate_configuration_override()",
        "tagekyc.c6ba_require_management_event()",
        "tagekyc.c6ba_require_capability_event()",
        "tagekyc.c6ba_require_redemption_event()",
        "tagekyc.c6ba_require_rotation_completion_event()",
        "tagekyc.c6ba_require_root_event()",
        "tagekyc.c6ba_root_provision_platform_credential(uuid, uuid, timestamp with time zone, text, bytea, integer, bytea, timestamp with time zone)",
        "tagekyc.c6ba_root_revoke_platform_credential(uuid, uuid, bigint, text, bytea, timestamp with time zone)",
        "tagekyc.capture_runtime_issue_bootstrap(uuid, uuid, text, uuid, bigint, uuid, bigint, uuid, bigint, timestamp with time zone, bytea, text, bytea, integer, bytea, timestamp with time zone)",
        "tagekyc.capture_runtime_revoke_bootstrap(uuid, uuid, uuid, bigint, text, bytea, timestamp with time zone)",
        "tagekyc.capture_runtime_redeem_bootstrap(uuid, uuid, bytea, uuid, bytea, bytea, timestamp with time zone, bytea, bytea, bytea, timestamp with time zone)",
        "tagekyc.c6ba_transition_runtime_lifecycle(uuid, uuid, uuid, bigint, text, bytea, timestamp with time zone, text, text, text, boolean)",
        "tagekyc.capture_runtime_suspend(uuid, uuid, uuid, bigint, text, bytea, timestamp with time zone)",
        "tagekyc.capture_runtime_reactivate(uuid, uuid, uuid, bigint, text, bytea, timestamp with time zone)",
        "tagekyc.capture_runtime_revoke(uuid, uuid, uuid, bigint, text, bytea, timestamp with time zone)",
        "tagekyc.capture_runtime_retire(uuid, uuid, uuid, bigint, text, bytea, timestamp with time zone)",
        "tagekyc.capture_runtime_authorize_rotation(uuid, uuid, uuid, uuid, uuid, bigint, bigint, timestamp with time zone, bytea, timestamp with time zone)",
        "tagekyc.c6ba_assert_current_operator(uuid, timestamp with time zone)",
        "tagekyc.capture_runtime_revoke_rotation(uuid, uuid, uuid, bigint, text, bytea, timestamp with time zone)",
        "tagekyc.capture_runtime_complete_rotation(uuid, uuid, bigint, uuid, uuid, bytea, bytea, bytea, bytea, timestamp with time zone)",
        "tagekyc.capture_runtime_replay_completed_rotation(uuid, uuid, bigint, uuid, uuid, bytea, bytea, bytea, timestamp with time zone)",
        "tagekyc.capture_runtime_publish_trust_profile(uuid, uuid, uuid, bigint, timestamp with time zone, timestamp with time zone, text, boolean, boolean, boolean, bytea, timestamp with time zone)",
        "tagekyc.capture_runtime_publish_role_policy(uuid, uuid, uuid, bigint, timestamp with time zone, text[], bytea, timestamp with time zone)",
        "tagekyc.capture_runtime_assign_role_policy(uuid, uuid, uuid, uuid, bigint, bigint, bytea, timestamp with time zone)",
        "tagekyc.capture_runtime_assign_configuration(uuid, uuid, uuid, uuid, bigint, bigint, uuid, bytea, timestamp with time zone)",
        "tagekyc.capture_runtime_publish_configuration(uuid, uuid, uuid, bigint, timestamp with time zone, timestamp with time zone, boolean, integer, integer, integer, integer, integer, bigint, integer, bigint, integer, bytea, timestamp with time zone)",
        "tagekyc.capture_runtime_issue_or_replace_capability(uuid, uuid, text, uuid, bigint, uuid, uuid, text, bytea, integer, bytea, timestamp with time zone)",
        "tagekyc.capture_runtime_resolve_capability_verifier(uuid)",
        "tagekyc.capture_runtime_bind_capability(uuid, uuid, uuid, bigint, uuid, boolean, uuid, bytea, timestamp with time zone)",
        "tagekyc.capture_runtime_reconcile_binding(uuid, uuid, uuid, bigint, uuid, uuid, timestamp with time zone)",
        "tagekyc.capture_runtime_materialize_capability_expiry(uuid, uuid, timestamp with time zone, uuid)",
        "tagekyc.capture_runtime_resolve_configuration(uuid, uuid, uuid, bigint, timestamp with time zone)",
        "tagekyc.capture_runtime_read_readiness(uuid, timestamp with time zone)",
        "tagekyc.capture_runtime_cancel_session_with_capability(uuid, uuid, text, text, text, timestamp with time zone, text, uuid)",
        "tagekyc.capture_runtime_validate_append_authority(uuid, uuid, uuid, bigint, uuid, text, timestamp with time zone)",
        "tagekyc.capture_runtime_read_cutover_state(text, timestamp with time zone)",
        "tagekyc.platform_operator_authenticate(text, timestamp with time zone)",
        "tagekyc.capture_runtime_resolve_verifier(uuid, bigint, timestamp with time zone)",
        "tagekyc.capture_runtime_resolve_bootstrap_verifier(uuid)",
        "tagekyc.capture_runtime_claim_nonce(uuid, uuid, uuid, bigint, text, bytea, timestamp with time zone, timestamp with time zone)",
        "tagekyc.capture_runtime_claim_rotation_completion_nonce(uuid, bigint, uuid, uuid, bytea, bytea, bytea, bytea, timestamp with time zone, timestamp with time zone)",
        "tagekyc.capture_runtime_cleanup_nonces(timestamp with time zone, integer)",
        "tagekyc.capture_runtime_revoke_credential(uuid, uuid, uuid, uuid, uuid, bigint, bigint, text, bytea, timestamp with time zone)",
    ];
    internal static readonly string[] Grants =
    [
        "tagekyc.c6ba_roles_are_canonical(text[])|",
        "tagekyc.c6ba_reject_row_mutation()|",
        "tagekyc.c6ba_validate_current_generation()|",
        "tagekyc.c6ba_validate_capability_graph()|",
        "tagekyc.c6ba_validate_configuration_override()|",
        "tagekyc.c6ba_require_management_event()|",
        "tagekyc.c6ba_require_capability_event()|",
        "tagekyc.c6ba_require_redemption_event()|",
        "tagekyc.c6ba_require_rotation_completion_event()|",
        "tagekyc.c6ba_require_root_event()|",
        "tagekyc.c6ba_root_provision_platform_credential(uuid, uuid, timestamp with time zone, text, bytea, integer, bytea, timestamp with time zone)|tagekyc_capture_runtime_operator",
        "tagekyc.c6ba_root_revoke_platform_credential(uuid, uuid, bigint, text, bytea, timestamp with time zone)|tagekyc_capture_runtime_operator",
        "tagekyc.capture_runtime_issue_bootstrap(uuid, uuid, text, uuid, bigint, uuid, bigint, uuid, bigint, timestamp with time zone, bytea, text, bytea, integer, bytea, timestamp with time zone)|tagekyc_capture_runtime_operator",
        "tagekyc.capture_runtime_revoke_bootstrap(uuid, uuid, uuid, bigint, text, bytea, timestamp with time zone)|tagekyc_capture_runtime_operator",
        "tagekyc.capture_runtime_redeem_bootstrap(uuid, uuid, bytea, uuid, bytea, bytea, timestamp with time zone, bytea, bytea, bytea, timestamp with time zone)|tagekyc_capture_runtime_application",
        "tagekyc.c6ba_transition_runtime_lifecycle(uuid, uuid, uuid, bigint, text, bytea, timestamp with time zone, text, text, text, boolean)|",
        "tagekyc.capture_runtime_suspend(uuid, uuid, uuid, bigint, text, bytea, timestamp with time zone)|tagekyc_capture_runtime_operator",
        "tagekyc.capture_runtime_reactivate(uuid, uuid, uuid, bigint, text, bytea, timestamp with time zone)|tagekyc_capture_runtime_operator",
        "tagekyc.capture_runtime_revoke(uuid, uuid, uuid, bigint, text, bytea, timestamp with time zone)|tagekyc_capture_runtime_operator",
        "tagekyc.capture_runtime_retire(uuid, uuid, uuid, bigint, text, bytea, timestamp with time zone)|tagekyc_capture_runtime_operator",
        "tagekyc.capture_runtime_authorize_rotation(uuid, uuid, uuid, uuid, uuid, bigint, bigint, timestamp with time zone, bytea, timestamp with time zone)|tagekyc_capture_runtime_operator",
        "tagekyc.c6ba_assert_current_operator(uuid, timestamp with time zone)|",
        "tagekyc.capture_runtime_revoke_rotation(uuid, uuid, uuid, bigint, text, bytea, timestamp with time zone)|tagekyc_capture_runtime_operator",
        "tagekyc.capture_runtime_complete_rotation(uuid, uuid, bigint, uuid, uuid, bytea, bytea, bytea, bytea, timestamp with time zone)|tagekyc_capture_runtime_application",
        "tagekyc.capture_runtime_replay_completed_rotation(uuid, uuid, bigint, uuid, uuid, bytea, bytea, bytea, timestamp with time zone)|tagekyc_capture_runtime_application",
        "tagekyc.capture_runtime_publish_trust_profile(uuid, uuid, uuid, bigint, timestamp with time zone, timestamp with time zone, text, boolean, boolean, boolean, bytea, timestamp with time zone)|tagekyc_capture_runtime_operator",
        "tagekyc.capture_runtime_publish_role_policy(uuid, uuid, uuid, bigint, timestamp with time zone, text[], bytea, timestamp with time zone)|tagekyc_capture_runtime_operator",
        "tagekyc.capture_runtime_assign_role_policy(uuid, uuid, uuid, uuid, bigint, bigint, bytea, timestamp with time zone)|tagekyc_capture_runtime_operator",
        "tagekyc.capture_runtime_assign_configuration(uuid, uuid, uuid, uuid, bigint, bigint, uuid, bytea, timestamp with time zone)|tagekyc_capture_runtime_operator",
        "tagekyc.capture_runtime_publish_configuration(uuid, uuid, uuid, bigint, timestamp with time zone, timestamp with time zone, boolean, integer, integer, integer, integer, integer, bigint, integer, bigint, integer, bytea, timestamp with time zone)|tagekyc_capture_runtime_operator",
        "tagekyc.capture_runtime_issue_or_replace_capability(uuid, uuid, text, uuid, bigint, uuid, uuid, text, bytea, integer, bytea, timestamp with time zone)|tagekyc_capture_runtime_application,tagekyc_runtime",
        "tagekyc.capture_runtime_resolve_capability_verifier(uuid)|tagekyc_capture_runtime_application",
        "tagekyc.capture_runtime_bind_capability(uuid, uuid, uuid, bigint, uuid, boolean, uuid, bytea, timestamp with time zone)|tagekyc_capture_runtime_application",
        "tagekyc.capture_runtime_reconcile_binding(uuid, uuid, uuid, bigint, uuid, uuid, timestamp with time zone)|tagekyc_capture_runtime_application",
        "tagekyc.capture_runtime_materialize_capability_expiry(uuid, uuid, timestamp with time zone, uuid)|tagekyc_capture_runtime_application",
        "tagekyc.capture_runtime_resolve_configuration(uuid, uuid, uuid, bigint, timestamp with time zone)|tagekyc_capture_runtime_application",
        "tagekyc.capture_runtime_read_readiness(uuid, timestamp with time zone)|tagekyc_capture_runtime_operator",
        "tagekyc.capture_runtime_cancel_session_with_capability(uuid, uuid, text, text, text, timestamp with time zone, text, uuid)|tagekyc_capture_runtime_application,tagekyc_runtime",
        "tagekyc.capture_runtime_validate_append_authority(uuid, uuid, uuid, bigint, uuid, text, timestamp with time zone)|tagekyc_runtime",
        "tagekyc.capture_runtime_read_cutover_state(text, timestamp with time zone)|tagekyc_capture_runtime_application",
        "tagekyc.platform_operator_authenticate(text, timestamp with time zone)|tagekyc_capture_runtime_authenticator",
        "tagekyc.capture_runtime_resolve_verifier(uuid, bigint, timestamp with time zone)|tagekyc_capture_runtime_authenticator",
        "tagekyc.capture_runtime_resolve_bootstrap_verifier(uuid)|tagekyc_capture_runtime_application",
        "tagekyc.capture_runtime_claim_nonce(uuid, uuid, uuid, bigint, text, bytea, timestamp with time zone, timestamp with time zone)|tagekyc_capture_runtime_authenticator",
        "tagekyc.capture_runtime_claim_rotation_completion_nonce(uuid, bigint, uuid, uuid, bytea, bytea, bytea, bytea, timestamp with time zone, timestamp with time zone)|tagekyc_capture_runtime_authenticator",
        "tagekyc.capture_runtime_cleanup_nonces(timestamp with time zone, integer)|tagekyc_capture_runtime_authenticator",
        "tagekyc.capture_runtime_revoke_credential(uuid, uuid, uuid, uuid, uuid, bigint, bigint, text, bytea, timestamp with time zone)|tagekyc_capture_runtime_operator",
    ];
}
