// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TagEkyc.Infrastructure.Persistence;

#nullable disable

namespace TagEkyc.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TagEkycDbContext))]
    [Migration("20260721070118_Tip88AE2PolicyPermitTtlField")]
    partial class Tip88AE2PolicyPermitTtlField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tagekyc")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.ApiKeyRow", b =>
                {
                    b.Property<Guid>("ApiKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AllowedCaptureAgentIdsJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("AllowedClientApplicationIdsJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("CallerCategory")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ClientApplicationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CredentialRef")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CredentialStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CredentialType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("KeyHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("MtlsSubjectDn")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("OAuthClientId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScopesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("ApiKeyId");

                    b.HasIndex("KeyPrefix")
                        .IsUnique();

                    b.ToTable("api_keys", "tagekyc", t =>
                        {
                            t.HasCheckConstraint("CK_api_keys_KeyHash_Length", "octet_length(\"KeyHash\") = 32");
                        });
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.AppendIdempotencyRecordRow", b =>
                {
                    b.Property<Guid>("VerificationSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EndpointKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("MintedId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubmissionSlot")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("VerificationSessionId", "IdempotencyKey");

                    b.HasIndex("MintedId");

                    b.HasIndex("VerificationSessionId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("append_idempotency_records", "tagekyc");
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.AuditEventRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ClientApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EventPayloadHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EventPayloadRef")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("VerificationSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VerificationSessionId");

                    b.ToTable("audit_events", "tagekyc");
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.CaptureArtifactRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArtifactHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ArtifactType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CaptureAgentId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CaptureSource")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetadataHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("QualityState")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RetryReasonCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("VaultRef")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("VerificationSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VerificationSessionId");

                    b.ToTable("capture_artifacts", "tagekyc");
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.EvidenceManifestRow", b =>
                {
                    b.Property<Guid>("EvidencePackageId")
                        .HasColumnType("uuid");

                    b.Property<string>("AuditEventRefsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("CanonicalizationScheme")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EvidencePackageSignatureStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("EvidenceRefsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("HashAlgorithm")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("KeyId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ManifestHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PackageHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PackageVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PublicKeyFingerprint")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PublicKeyJwk")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid>("ResultRef")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("SignatureAlgorithm")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SignatureFormat")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SignatureScheme")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SignatureValue")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("SignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VerificationSessionId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("EvidencePackageId");

                    b.HasIndex("SessionGuid");

                    b.ToTable("evidence_manifests", "tagekyc");
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.EvidencePackageRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuditEventRefsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("CanonicalizationScheme")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EvidencePackageSignatureStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("EvidenceRefsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("HashAlgorithm")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ManifestHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PackageHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PackageVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ResultRef")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VerificationSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VerificationSessionId");

                    b.ToTable("evidence_packages", "tagekyc");
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.EvidenceResultRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Confidence")
                        .HasColumnType("numeric");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EngineName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EngineVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("InputCaptureArtifactIdsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("PayloadHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PayloadSignatureStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ReasonCodesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ResultType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RetryReasonCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SanitizedSummaryRef")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid?>("VerificationCheckId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VerificationSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VerificationSessionId");

                    b.ToTable("evidence_results", "tagekyc");
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportControlAuthorityRow", b =>
                {
                    b.Property<Guid>("AuthorityEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DecisionRef")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecordedByPrincipalId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequirementType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ScopeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("AuthorityEventId");

                    b.ToTable("raw_export_control_authorities", "tagekyc", t =>
                        {
                            t.HasCheckConstraint("CK_raw_export_control_authorities_AuthorityType", "\"AuthorityType\" IN ('GrantAdmin','RecorderAuthorityAdmin','ActivationAuthority','FulfillmentRecorder')");

                            t.HasCheckConstraint("CK_raw_export_control_authorities_DecisionRef_NotBlank", "btrim(\"DecisionRef\") <> ''");

                            t.HasCheckConstraint("CK_raw_export_control_authorities_EventType", "\"EventType\" IN ('Granted','Revoked')");

                            t.HasCheckConstraint("CK_raw_export_control_authorities_RequirementShape", "(\n                    \"AuthorityType\" = 'FulfillmentRecorder'\n                    AND \"RequirementType\" IN ('LegalApproval','Dpia','CrossBorderAssessment','RetentionSchedule')\n                ) OR (\n                    \"AuthorityType\" <> 'FulfillmentRecorder'\n                    AND \"RequirementType\" IS NULL\n                )");

                            t.HasCheckConstraint("CK_raw_export_control_authorities_ScopeShape", "(\n                    \"ScopeType\" = 'Global' AND \"ScopeId\" IS NULL\n                ) OR (\n                    \"ScopeType\" = 'Policy' AND \"ScopeId\" IS NOT NULL\n                )");

                            t.HasCheckConstraint("CK_raw_export_control_authorities_ScopeType", "\"ScopeType\" IN ('Policy','Global')");
                        });
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportFulfillmentRow", b =>
                {
                    b.Property<Guid>("FulfillmentEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArtifactRef")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ArtifactVersion")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FulfillmentDecisionRef")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid");

                    b.Property<int>("PolicyVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecordedByPrincipalId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequirementType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<int?>("SupersedesRevision")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetRevision")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ValidFromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ValidUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("FulfillmentEventId");

                    b.HasIndex("PolicyId", "PolicyVersion", "RequirementType", "Revision")
                        .IsUnique();

                    b.ToTable("raw_export_fulfillments", "tagekyc", t =>
                        {
                            t.HasCheckConstraint("CK_raw_export_fulfillments_DecisionRef_NotBlank", "btrim(\"FulfillmentDecisionRef\") <> ''");

                            t.HasCheckConstraint("CK_raw_export_fulfillments_EventShape", "(\n                    \"EventType\" = 'Accepted'\n                    AND \"ArtifactRef\" IS NOT NULL\n                    AND btrim(\"ArtifactRef\") <> ''\n                    AND \"ArtifactVersion\" IS NOT NULL\n                    AND btrim(\"ArtifactVersion\") <> ''\n                    AND \"ValidFromUtc\" IS NOT NULL\n                    AND \"TargetRevision\" IS NULL\n                ) OR (\n                    \"EventType\" = 'Withdrawn'\n                    AND \"TargetRevision\" IS NOT NULL\n                    AND \"ArtifactRef\" IS NULL\n                    AND \"ArtifactVersion\" IS NULL\n                    AND \"ValidFromUtc\" IS NULL\n                    AND \"ValidUntilUtc\" IS NULL\n                    AND \"SupersedesRevision\" IS NULL\n                )");

                            t.HasCheckConstraint("CK_raw_export_fulfillments_EventType", "\"EventType\" IN ('Accepted','Withdrawn')");

                            t.HasCheckConstraint("CK_raw_export_fulfillments_RequirementType", "\"RequirementType\" IN ('LegalApproval','Dpia','CrossBorderAssessment','RetentionSchedule')");

                            t.HasCheckConstraint("CK_raw_export_fulfillments_Validity", "\"ValidUntilUtc\" IS NULL OR \"ValidFromUtc\" IS NULL OR \"ValidUntilUtc\" > \"ValidFromUtc\"");
                        });
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportGrantRow", b =>
                {
                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid");

                    b.Property<int>("PolicyVersion")
                        .HasColumnType("integer");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ClientApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("DecisionRef")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecordedByPrincipalId")
                        .HasColumnType("uuid");

                    b.HasKey("PrincipalId", "PolicyId", "PolicyVersion", "Revision");

                    b.HasIndex("PolicyId", "PolicyVersion");

                    b.ToTable("raw_export_grants", "tagekyc", t =>
                        {
                            t.HasCheckConstraint("CK_raw_export_grants_DecisionRef_NotBlank", "btrim(\"DecisionRef\") <> ''");

                            t.HasCheckConstraint("CK_raw_export_grants_EventType", "\"EventType\" IN ('Granted','Revoked')");
                        });
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportPolicyAllowedClassRow", b =>
                {
                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid");

                    b.Property<int>("PolicyVersion")
                        .HasColumnType("integer");

                    b.Property<string>("RawClass")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PolicyId", "PolicyVersion", "RawClass");

                    b.ToTable("raw_export_policy_allowed_classes", "tagekyc", t =>
                        {
                            t.HasCheckConstraint("CK_raw_export_policy_allowed_classes_RawClass", "\"RawClass\" IN ('ChipDg1','ChipDg2Portrait','ChipDg13','ChipDg15','ChipSod','AaChallenge','AaResponse','LiveSelfieImage','LivenessMedia','HandSignatureImage')");
                        });
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportPolicyClosureRow", b =>
                {
                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid");

                    b.Property<int>("PolicyVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClosedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ClosureType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DecisionRef")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("PolicyId", "PolicyVersion");

                    b.ToTable("raw_export_policy_closures", "tagekyc", t =>
                        {
                            t.HasCheckConstraint("CK_raw_export_policy_closures_ClosureType", "\"ClosureType\" IN ('CatalogApproved','Abandoned')");

                            t.HasCheckConstraint("CK_raw_export_policy_closures_DecisionRef_NotBlank", "btrim(\"DecisionRef\") <> ''");

                            t.HasCheckConstraint("CK_raw_export_policy_closures_Principal_NotBlank", "btrim(\"ClosedByPrincipalId\") <> ''");
                        });
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportPolicyLifecycleRow", b =>
                {
                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid");

                    b.Property<int>("PolicyVersion")
                        .HasColumnType("integer");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<string>("DecisionRef")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecordedByPrincipalId")
                        .HasColumnType("uuid");

                    b.HasKey("PolicyId", "PolicyVersion", "Revision");

                    b.ToTable("raw_export_policy_lifecycle", "tagekyc", t =>
                        {
                            t.HasCheckConstraint("CK_raw_export_policy_lifecycle_DecisionRef_NotBlank", "btrim(\"DecisionRef\") <> ''");

                            t.HasCheckConstraint("CK_raw_export_policy_lifecycle_EventType", "\"EventType\" IN ('Activated','Suspended','Revoked')");
                        });
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportPolicyRequirementRow", b =>
                {
                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid");

                    b.Property<int>("PolicyVersion")
                        .HasColumnType("integer");

                    b.Property<string>("RequirementType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PolicyId", "PolicyVersion", "RequirementType");

                    b.ToTable("raw_export_policy_requirements", "tagekyc", t =>
                        {
                            t.HasCheckConstraint("CK_raw_export_policy_requirements_RequirementType", "\"RequirementType\" IN ('LegalApproval','ConsentArtifact','Dpia','CrossBorderAssessment','RetentionSchedule')");
                        });
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportPolicyVersionRow", b =>
                {
                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid");

                    b.Property<int>("PolicyVersion")
                        .HasColumnType("integer");

                    b.Property<string>("ConsentRequirement")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ControllerEntityRef")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ControllerJurisdiction")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("ControllerRole")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("PermitTtlSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("ProcessingInfrastructureJurisdiction")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RecipientAssuranceRequirement")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RecipientCategory")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RecipientJurisdiction")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("RequirementRuleSetId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("RequirementRuleSetVersion")
                        .HasColumnType("integer");

                    b.Property<string>("RetentionProfileRef")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RetentionPurposeCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TransferLegalBasisCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TransferScenarioCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("PolicyId", "PolicyVersion");

                    b.HasIndex("RequirementRuleSetId", "RequirementRuleSetVersion");

                    b.ToTable("raw_export_policy_versions", "tagekyc", t =>
                        {
                            t.HasCheckConstraint("CK_raw_export_policy_versions_ConsentRequirement", "\"ConsentRequirement\" IN ('Required','NotRequired')");

                            t.HasCheckConstraint("CK_raw_export_policy_versions_Mode", "\"Mode\" IN ('ExternalExportOnlyNoRetain','EncryptedExportPacket','EncryptedRawVaultRetained')");

                            t.HasCheckConstraint("CK_raw_export_policy_versions_Retention", "(\n                    \"Mode\" = 'ExternalExportOnlyNoRetain' AND \"RetentionProfileRef\" IS NULL\n                ) OR (\n                    \"Mode\" IN ('EncryptedExportPacket','EncryptedRawVaultRetained') AND \"RetentionProfileRef\" IS NOT NULL\n                )");
                        });
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportRequirementRuleRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequirementType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RuleSelector")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RuleSetId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("RuleSetVersion")
                        .HasColumnType("integer");

                    b.Property<string>("SelectorOperand")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("RuleSetId", "RuleSetVersion");

                    b.ToTable("raw_export_requirement_rules", "tagekyc", t =>
                        {
                            t.HasCheckConstraint("CK_raw_export_requirement_rules_RequirementType", "\"RequirementType\" IN ('LegalApproval','ConsentArtifact','Dpia','CrossBorderAssessment','RetentionSchedule')");

                            t.HasCheckConstraint("CK_raw_export_requirement_rules_RuleSelector", "\"RuleSelector\" IN ('Always','ModeEquals','ConsentRequired','AnyJurisdictionForeign')");

                            t.HasCheckConstraint("CK_raw_export_requirement_rules_RuleSetId", "\"RuleSetId\" = 'RAW_EXPORT_REQUIREMENTS'");

                            t.HasCheckConstraint("CK_raw_export_requirement_rules_SelectorOperand", "(\n                    \"RuleSelector\" = 'ModeEquals' AND \"SelectorOperand\" IN ('ExternalExportOnlyNoRetain','EncryptedExportPacket','EncryptedRawVaultRetained')\n                ) OR (\n                    \"RuleSelector\" IN ('Always','ConsentRequired','AnyJurisdictionForeign') AND \"SelectorOperand\" IS NULL\n                )");
                        });
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportRequirementRuleSetRow", b =>
                {
                    b.Property<string>("RuleSetId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("RuleSetVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HomeJurisdictionCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("MigrationRef")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("RuleSetId", "RuleSetVersion");

                    b.ToTable("raw_export_requirement_rule_sets", "tagekyc", t =>
                        {
                            t.HasCheckConstraint("CK_raw_export_requirement_rule_sets_HomeJurisdictionCode", "\"HomeJurisdictionCode\" ~ '^[A-Z]{2}$'");

                            t.HasCheckConstraint("CK_raw_export_requirement_rule_sets_RuleSetId", "\"RuleSetId\" = 'RAW_EXPORT_REQUIREMENTS'");
                        });
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportSubjectConsentAuthorityRow", b =>
                {
                    b.Property<Guid>("AuthorityEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorityPrincipalId")
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ClientApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("DecisionRef")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecordedByPrincipalId")
                        .HasColumnType("uuid");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetRevision")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ValidFromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ValidUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AuthorityEventId");

                    b.HasIndex("AuthorityPrincipalId", "ClientApplicationId", "AuthorityType", "Revision")
                        .IsUnique();

                    b.ToTable("raw_export_subject_consent_authorities", "tagekyc", t =>
                        {
                            t.HasCheckConstraint("CK_raw_export_subject_consent_authorities_AuthorityType", "\"AuthorityType\" IN ('SubjectConsentRecorder','SubjectConsentWithdrawer')");

                            t.HasCheckConstraint("CK_raw_export_subject_consent_authorities_DecisionRef_NotBlank", "\"DecisionRef\" IS NULL OR btrim(\"DecisionRef\") <> ''");

                            t.HasCheckConstraint("CK_raw_export_subject_consent_authorities_EventShape", "(\n    \"EventType\" = 'Granted'\n    AND \"TargetRevision\" IS NULL\n    AND \"ValidFromUtc\" IS NOT NULL\n    AND (\"ValidUntilUtc\" IS NULL OR \"ValidUntilUtc\" > \"ValidFromUtc\")\n) OR (\n    \"EventType\" = 'Revoked'\n    AND \"TargetRevision\" IS NOT NULL\n    AND \"ValidFromUtc\" IS NULL\n    AND \"ValidUntilUtc\" IS NULL\n)");

                            t.HasCheckConstraint("CK_raw_export_subject_consent_authorities_EventType", "\"EventType\" IN ('Granted','Revoked')");
                        });
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportSubjectConsentClassRow", b =>
                {
                    b.Property<Guid>("SubjectConsentRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("RawClass")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SubjectConsentRecordId", "RawClass");

                    b.ToTable("raw_export_subject_consent_classes", "tagekyc", t =>
                        {
                            t.HasCheckConstraint("CK_raw_export_subject_consent_classes_RawClass", "\"RawClass\" IN ('ChipDg1','ChipDg2Portrait','ChipDg13','ChipDg15','ChipSod','AaChallenge','AaResponse','LiveSelfieImage','LivenessMedia','HandSignatureImage')");
                        });
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportSubjectConsentEventRow", b =>
                {
                    b.Property<Guid>("SubjectConsentRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CapturedByPrincipalId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("ConsentScopeHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ConsentTextContentHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ConsentTextVersion")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DecisionRef")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ExternalConsentArtifactRef")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid");

                    b.Property<int>("PolicyVersion")
                        .HasColumnType("integer");

                    b.Property<string>("PurposeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("RecipientClientApplicationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<string>("SubjectRef")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("TargetRevision")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ValidFromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ValidUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VerificationSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WithdrawnByPrincipalId")
                        .HasColumnType("uuid");

                    b.HasKey("SubjectConsentRecordId");

                    b.HasIndex("VerificationSessionId", "SubjectRef", "PolicyId", "PolicyVersion", "PurposeCode", "RecipientClientApplicationId", "Revision")
                        .IsUnique();

                    b.ToTable("raw_export_subject_consent_events", "tagekyc", t =>
                        {
                            t.HasCheckConstraint("CK_raw_export_subject_consent_events_EventShape", "(\n    \"EventType\" = 'Granted'\n    AND \"TargetRevision\" IS NULL\n    AND \"ConsentTextVersion\" IS NOT NULL AND btrim(\"ConsentTextVersion\") <> ''\n    AND \"ConsentTextContentHash\" IS NOT NULL AND btrim(\"ConsentTextContentHash\") <> ''\n    AND \"ExternalConsentArtifactRef\" IS NOT NULL AND btrim(\"ExternalConsentArtifactRef\") <> ''\n    AND (\"DecisionRef\" IS NULL OR btrim(\"DecisionRef\") <> '')\n    AND \"ValidFromUtc\" IS NOT NULL\n    AND \"CapturedAtUtc\" IS NOT NULL\n    AND \"CapturedByPrincipalId\" IS NOT NULL\n    AND \"WithdrawnByPrincipalId\" IS NULL\n    AND (\"ValidUntilUtc\" IS NULL OR \"ValidUntilUtc\" > \"ValidFromUtc\")\n) OR (\n    \"EventType\" = 'Withdrawn'\n    AND \"TargetRevision\" IS NOT NULL\n    AND \"ConsentTextVersion\" IS NULL\n    AND \"ConsentTextContentHash\" IS NULL\n    AND \"ValidFromUtc\" IS NULL\n    AND \"ValidUntilUtc\" IS NULL\n    AND \"CapturedAtUtc\" IS NULL\n    AND \"CapturedByPrincipalId\" IS NULL\n    AND \"WithdrawnByPrincipalId\" IS NOT NULL\n)");

                            t.HasCheckConstraint("CK_raw_export_subject_consent_events_EventType", "\"EventType\" IN ('Granted','Withdrawn')");

                            t.HasCheckConstraint("CK_raw_export_subject_consent_events_HashLength", "octet_length(\"ConsentScopeHash\") = 32");

                            t.HasCheckConstraint("CK_raw_export_subject_consent_events_PurposeCode", "\"PurposeCode\" = 'SubjectRawBiometricExport'");
                        });
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.VerificationDecisionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssuranceLevel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CompletedChecksJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecisionReasonCodesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("FailedChecksJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RetryReasonCodesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<decimal?>("RiskScore")
                        .HasColumnType("numeric");

                    b.Property<Guid>("VerificationSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VerificationSessionId");

                    b.ToTable("verification_decisions", "tagekyc");
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.VerificationSessionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AccessAuditRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("ActorCategory")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ActorId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("AssuranceLevel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("BindingNonceHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("ClientApplicationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletionEligibility")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("EvidencePackageHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("EvidencePackageId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalSessionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ExternalTransactionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("FinalDecisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("LegalHoldStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ManifestHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PolicySnapshotId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PurgeBlockReason")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RequiredChecksJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RetentionClass")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SubjectRef")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ClientApplicationId", "ExternalSessionId")
                        .IsUnique()
                        .HasFilter("\"ExternalSessionId\" IS NOT NULL");

                    b.ToTable("verification_sessions", "tagekyc");
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.AppendIdempotencyRecordRow", b =>
                {
                    b.HasOne("TagEkyc.Infrastructure.Persistence.Entities.VerificationSessionRow", null)
                        .WithMany()
                        .HasForeignKey("VerificationSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.AuditEventRow", b =>
                {
                    b.HasOne("TagEkyc.Infrastructure.Persistence.Entities.VerificationSessionRow", null)
                        .WithMany()
                        .HasForeignKey("VerificationSessionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.CaptureArtifactRow", b =>
                {
                    b.HasOne("TagEkyc.Infrastructure.Persistence.Entities.VerificationSessionRow", null)
                        .WithMany()
                        .HasForeignKey("VerificationSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.EvidenceManifestRow", b =>
                {
                    b.HasOne("TagEkyc.Infrastructure.Persistence.Entities.EvidencePackageRow", null)
                        .WithOne()
                        .HasForeignKey("TagEkyc.Infrastructure.Persistence.Entities.EvidenceManifestRow", "EvidencePackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.EvidencePackageRow", b =>
                {
                    b.HasOne("TagEkyc.Infrastructure.Persistence.Entities.VerificationSessionRow", null)
                        .WithMany()
                        .HasForeignKey("VerificationSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.EvidenceResultRow", b =>
                {
                    b.HasOne("TagEkyc.Infrastructure.Persistence.Entities.VerificationSessionRow", null)
                        .WithMany()
                        .HasForeignKey("VerificationSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportFulfillmentRow", b =>
                {
                    b.HasOne("TagEkyc.Infrastructure.Persistence.Entities.RawExportPolicyVersionRow", null)
                        .WithMany()
                        .HasForeignKey("PolicyId", "PolicyVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportGrantRow", b =>
                {
                    b.HasOne("TagEkyc.Infrastructure.Persistence.Entities.RawExportPolicyVersionRow", null)
                        .WithMany()
                        .HasForeignKey("PolicyId", "PolicyVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportPolicyAllowedClassRow", b =>
                {
                    b.HasOne("TagEkyc.Infrastructure.Persistence.Entities.RawExportPolicyVersionRow", null)
                        .WithMany()
                        .HasForeignKey("PolicyId", "PolicyVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportPolicyClosureRow", b =>
                {
                    b.HasOne("TagEkyc.Infrastructure.Persistence.Entities.RawExportPolicyVersionRow", null)
                        .WithOne()
                        .HasForeignKey("TagEkyc.Infrastructure.Persistence.Entities.RawExportPolicyClosureRow", "PolicyId", "PolicyVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportPolicyLifecycleRow", b =>
                {
                    b.HasOne("TagEkyc.Infrastructure.Persistence.Entities.RawExportPolicyVersionRow", null)
                        .WithMany()
                        .HasForeignKey("PolicyId", "PolicyVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportPolicyRequirementRow", b =>
                {
                    b.HasOne("TagEkyc.Infrastructure.Persistence.Entities.RawExportPolicyVersionRow", null)
                        .WithMany()
                        .HasForeignKey("PolicyId", "PolicyVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportPolicyVersionRow", b =>
                {
                    b.HasOne("TagEkyc.Infrastructure.Persistence.Entities.RawExportRequirementRuleSetRow", null)
                        .WithMany()
                        .HasForeignKey("RequirementRuleSetId", "RequirementRuleSetVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportRequirementRuleRow", b =>
                {
                    b.HasOne("TagEkyc.Infrastructure.Persistence.Entities.RawExportRequirementRuleSetRow", null)
                        .WithMany()
                        .HasForeignKey("RuleSetId", "RuleSetVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportSubjectConsentClassRow", b =>
                {
                    b.HasOne("TagEkyc.Infrastructure.Persistence.Entities.RawExportSubjectConsentEventRow", null)
                        .WithMany()
                        .HasForeignKey("SubjectConsentRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.VerificationDecisionRow", b =>
                {
                    b.HasOne("TagEkyc.Infrastructure.Persistence.Entities.VerificationSessionRow", null)
                        .WithMany()
                        .HasForeignKey("VerificationSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
