// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TagEkyc.Infrastructure.Persistence;

#nullable disable

namespace TagEkyc.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TagEkycDbContext))]
    [Migration("20260722084729_Tip88B31RawExportAuthorizationSchema")]
    partial class Tip88B31RawExportAuthorizationSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tagekyc")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.ApiKeyRow", b =>
                {
                    b.Property<Guid>("ApiKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AllowedCaptureAgentIdsJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("AllowedClientApplicationIdsJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("CallerCategory")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ClientApplicationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CredentialRef")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CredentialStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CredentialType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("KeyHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("MtlsSubjectDn")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("OAuthClientId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScopesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("ApiKeyId");

                    b.HasIndex("KeyPrefix")
                        .IsUnique();

                    b.ToTable("api_keys", "tagekyc", t =>
                        {
                            t.HasCheckConstraint("CK_api_keys_KeyHash_Length", "octet_length(\"KeyHash\") = 32");
                        });
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.AppendIdempotencyRecordRow", b =>
                {
                    b.Property<Guid>("VerificationSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EndpointKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("MintedId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubmissionSlot")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("VerificationSessionId", "IdempotencyKey");

                    b.HasIndex("MintedId");

                    b.HasIndex("VerificationSessionId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("append_idempotency_records", "tagekyc");
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.AuditEventRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ClientApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EventPayloadHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EventPayloadRef")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("VerificationSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VerificationSessionId");

                    b.ToTable("audit_events", "tagekyc");
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.CaptureArtifactRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArtifactHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ArtifactType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CaptureAgentId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CaptureSource")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetadataHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("QualityState")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RetryReasonCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("VaultRef")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("VerificationSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VerificationSessionId");

                    b.ToTable("capture_artifacts", "tagekyc");
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.EvidenceManifestRow", b =>
                {
                    b.Property<Guid>("EvidencePackageId")
                        .HasColumnType("uuid");

                    b.Property<string>("AuditEventRefsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("CanonicalizationScheme")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EvidencePackageSignatureStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("EvidenceRefsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("HashAlgorithm")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("KeyId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ManifestHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PackageHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PackageVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PublicKeyFingerprint")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PublicKeyJwk")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid>("ResultRef")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("SignatureAlgorithm")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SignatureFormat")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SignatureScheme")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SignatureValue")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("SignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VerificationSessionId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("EvidencePackageId");

                    b.HasIndex("SessionGuid");

                    b.ToTable("evidence_manifests", "tagekyc");
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.EvidencePackageRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuditEventRefsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("CanonicalizationScheme")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EvidencePackageSignatureStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("EvidenceRefsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("HashAlgorithm")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ManifestHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PackageHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PackageVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ResultRef")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VerificationSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VerificationSessionId");

                    b.ToTable("evidence_packages", "tagekyc");
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.EvidenceResultRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Confidence")
                        .HasColumnType("numeric");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EngineName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EngineVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("InputCaptureArtifactIdsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("PayloadHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PayloadSignatureStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ReasonCodesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ResultType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RetryReasonCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SanitizedSummaryRef")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid?>("VerificationCheckId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VerificationSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VerificationSessionId");

                    b.ToTable("evidence_results", "tagekyc");
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportAuthorizationDecisionRow", b =>
                {
                    b.Property<Guid>("ExportDecisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApiKeyId")
                        .HasColumnType("uuid");

                    b.Property<int?>("BoundRuleSetVersion")
                        .HasColumnType("integer");

                    b.Property<Guid>("ClientApplicationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ConsentEvaluatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ConsentRevision")
                        .HasColumnType("integer");

                    b.Property<byte[]>("ConsentScopeHash")
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("ConsentValidFromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ConsentValidUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CurrentRuleSetVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("DecidedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DecisionExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EligibilityEvaluatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EligibilityPrimaryCause")
                        .HasColumnType("text");

                    b.Property<byte[]>("FingerprintHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid?>("GrantPolicyId")
                        .HasColumnType("uuid");

                    b.Property<int?>("GrantPolicyVersion")
                        .HasColumnType("integer");

                    b.Property<Guid?>("GrantPrincipalId")
                        .HasColumnType("uuid");

                    b.Property<int?>("GrantRevision")
                        .HasColumnType("integer");

                    b.Property<Guid?>("LifecyclePolicyId")
                        .HasColumnType("uuid");

                    b.Property<int?>("LifecyclePolicyVersion")
                        .HasColumnType("integer");

                    b.Property<int?>("LifecycleRevision")
                        .HasColumnType("integer");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid");

                    b.Property<int?>("PolicyPermitTtlSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("PolicyVersion")
                        .HasColumnType("integer");

                    b.Property<string>("PrimaryCause")
                        .HasColumnType("text");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid");

                    b.Property<string>("PurposeCode")
                        .HasColumnType("text");

                    b.Property<string>("RawClassSelectionMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RecipientClientApplicationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequestedVerificationSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ResolvedVerificationSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SessionOwnerClientApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("SessionState")
                        .HasColumnType("text");

                    b.Property<string>("SessionSubjectRef")
                        .HasColumnType("text");

                    b.Property<string>("SubjectConsentCause")
                        .HasColumnType("text");

                    b.Property<Guid?>("SubjectConsentRecordId")
                        .HasColumnType("uuid");

                    b.HasKey("ExportDecisionId")
                        .HasName("PK_raw_export_authorization_decisions");

                    b.HasIndex("ResolvedVerificationSessionId");

                    b.ToTable("raw_export_authorization_decisions", "tagekyc", t =>
                        {
                            t.HasCheckConstraint("CK_raw_export_authorization_decisions_ConsentScopeHash_len", "\"ConsentScopeHash\" IS NULL OR octet_length(\"ConsentScopeHash\") = 32");

                            t.HasCheckConstraint("CK_raw_export_authorization_decisions_EligibilityCause_enum", "\"EligibilityPrimaryCause\" IS NULL OR \"EligibilityPrimaryCause\" IN ('GrantMissing','GrantRevoked','PolicyNotActive','PolicyRevoked','PolicySuspended','NotCatalogApproved','StaleRuleSet','MissingOrInvalidFulfillment')");

                            t.HasCheckConstraint("CK_raw_export_authorization_decisions_FingerprintHash_len", "octet_length(\"FingerprintHash\") = 32");

                            t.HasCheckConstraint("CK_raw_export_authorization_decisions_Outcome_enum", "\"Outcome\" IN ('Authorized','Denied')");

                            t.HasCheckConstraint("CK_raw_export_authorization_decisions_PolicyVersion_range", "\"PolicyVersion\" >= 1");

                            t.HasCheckConstraint("CK_raw_export_authorization_decisions_PrimaryCause_enum", "\"PrimaryCause\" IS NULL OR \"PrimaryCause\" IN ('SESSION_NOT_FOUND','SESSION_NOT_OWNED','SESSION_NOT_COMPLETED','EXPORT_ELIGIBILITY_INACTIVE','POLICY_PERMIT_TTL_INVALID','REQUESTED_RAW_CLASSES_NOT_ALLOWED','SUBJECT_CONSENT_NOT_EFFECTIVE','SUBJECT_CONSENT_CLASS_COVERAGE_INSUFFICIENT')");

                            t.HasCheckConstraint("CK_raw_export_authorization_decisions_SelectionMode_enum", "\"RawClassSelectionMode\" IN ('DefaultPolicySet','ExplicitSubset')");

                            t.HasCheckConstraint("CK_raw_export_authorization_decisions_SessionState_enum", "\"SessionState\" IS NULL OR \"SessionState\" IN ('Created','InProgress','ReadyToComplete','Completed','Expired','Cancelled','TechnicalTerminal')");

                            t.HasCheckConstraint("CK_raw_export_authorization_decisions_SubjectConsentCause_enum", "\"SubjectConsentCause\" IS NULL OR \"SubjectConsentCause\" IN ('Missing','Withdrawn','Expired')");

                            t.HasCheckConstraint("CK_raw_export_authorization_decisions_row_shape", "(\"Outcome\" = 'Authorized' AND \"PrimaryCause\" IS NULL AND \"ResolvedVerificationSessionId\" IS NOT NULL AND \"SessionOwnerClientApplicationId\" IS NOT NULL AND \"SessionSubjectRef\" IS NOT NULL AND \"SessionState\" IS NOT NULL AND \"BoundRuleSetVersion\" IS NOT NULL AND \"CurrentRuleSetVersion\" IS NOT NULL AND \"EligibilityEvaluatedAtUtc\" IS NOT NULL AND \"GrantPrincipalId\" IS NOT NULL AND \"GrantPolicyId\" IS NOT NULL AND \"GrantPolicyVersion\" IS NOT NULL AND \"GrantRevision\" IS NOT NULL AND \"LifecyclePolicyId\" IS NOT NULL AND \"LifecyclePolicyVersion\" IS NOT NULL AND \"LifecycleRevision\" IS NOT NULL AND \"PurposeCode\" IS NOT NULL AND \"RecipientClientApplicationId\" IS NOT NULL AND \"ConsentScopeHash\" IS NOT NULL AND \"SubjectConsentRecordId\" IS NOT NULL AND \"ConsentRevision\" IS NOT NULL AND \"ConsentValidFromUtc\" IS NOT NULL AND \"ConsentEvaluatedAtUtc\" IS NOT NULL AND \"PolicyPermitTtlSeconds\" IS NOT NULL AND \"DecisionExpiresAtUtc\" IS NOT NULL) OR (\"Outcome\" = 'Denied' AND \"PrimaryCause\" IS NOT NULL AND \"DecisionExpiresAtUtc\" IS NULL)");
                        });
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportAuthorizationIdempotencyRow", b =>
                {
                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientApplicationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequestedVerificationSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExportDecisionId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("FingerprintHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("PrincipalId", "ClientApplicationId", "RequestedVerificationSessionId", "IdempotencyKey")
                        .HasName("PK_raw_export_authorization_idempotency");

                    b.HasAlternateKey("ExportDecisionId")
                        .HasName("UQ_raw_export_authorization_idempotency_ExportDecisionId");

                    b.ToTable("raw_export_authorization_idempotency", "tagekyc", t =>
                        {
                            t.HasCheckConstraint("CK_raw_export_authorization_idempotency_FingerprintHash_len", "octet_length(\"FingerprintHash\") = 32");
                        });
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportAuthorizationPermitRow", b =>
                {
                    b.Property<Guid>("PermitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorizationDecisionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DecisionExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid");

                    b.Property<int>("PolicyVersion")
                        .HasColumnType("integer");

                    b.Property<string>("PurposeCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RecipientClientApplicationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResolvedVerificationSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer");

                    b.Property<string>("SubjectRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PermitId")
                        .HasName("PK_raw_export_authorization_permits");

                    b.HasAlternateKey("AuthorizationDecisionId")
                        .HasName("UQ_raw_export_authorization_permits_AuthorizationDecisionId");

                    b.HasIndex("ResolvedVerificationSessionId");

                    b.ToTable("raw_export_authorization_permits", "tagekyc", t =>
                        {
                            t.HasCheckConstraint("CK_raw_export_authorization_permits_PolicyVersion_range", "\"PolicyVersion\" >= 1");

                            t.HasCheckConstraint("CK_raw_export_authorization_permits_SchemaVersion_eq1", "\"SchemaVersion\" = 1");
                        });
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportControlAuthorityRow", b =>
                {
                    b.Property<Guid>("AuthorityEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DecisionRef")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecordedByPrincipalId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequirementType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ScopeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("AuthorityEventId");

                    b.ToTable("raw_export_control_authorities", "tagekyc", t =>
                        {
                            t.HasCheckConstraint("CK_raw_export_control_authorities_AuthorityType", "\"AuthorityType\" IN ('GrantAdmin','RecorderAuthorityAdmin','ActivationAuthority','FulfillmentRecorder')");

                            t.HasCheckConstraint("CK_raw_export_control_authorities_DecisionRef_NotBlank", "btrim(\"DecisionRef\") <> ''");

                            t.HasCheckConstraint("CK_raw_export_control_authorities_EventType", "\"EventType\" IN ('Granted','Revoked')");

                            t.HasCheckConstraint("CK_raw_export_control_authorities_RequirementShape", "(\r\n                    \"AuthorityType\" = 'FulfillmentRecorder'\r\n                    AND \"RequirementType\" IN ('LegalApproval','Dpia','CrossBorderAssessment','RetentionSchedule')\r\n                ) OR (\r\n                    \"AuthorityType\" <> 'FulfillmentRecorder'\r\n                    AND \"RequirementType\" IS NULL\r\n                )");

                            t.HasCheckConstraint("CK_raw_export_control_authorities_ScopeShape", "(\r\n                    \"ScopeType\" = 'Global' AND \"ScopeId\" IS NULL\r\n                ) OR (\r\n                    \"ScopeType\" = 'Policy' AND \"ScopeId\" IS NOT NULL\r\n                )");

                            t.HasCheckConstraint("CK_raw_export_control_authorities_ScopeType", "\"ScopeType\" IN ('Policy','Global')");
                        });
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportDecisionClassRow", b =>
                {
                    b.Property<Guid>("ExportDecisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClassKind")
                        .HasColumnType("text");

                    b.Property<string>("RawClass")
                        .HasColumnType("text");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.HasKey("ExportDecisionId", "ClassKind", "RawClass")
                        .HasName("PK_raw_export_decision_classes");

                    b.HasAlternateKey("ExportDecisionId", "ClassKind", "Ordinal")
                        .HasName("UQ_raw_export_decision_classes_Ordinal");

                    b.ToTable("raw_export_decision_classes", "tagekyc", t =>
                        {
                            t.HasCheckConstraint("CK_raw_export_decision_classes_ClassKind_enum", "\"ClassKind\" IN ('PolicyAllowed','Requested','Effective','Consented','Authorized')");

                            t.HasCheckConstraint("CK_raw_export_decision_classes_Ordinal_nonneg", "\"Ordinal\" >= 0");

                            t.HasCheckConstraint("CK_raw_export_decision_classes_RawClass_enum", "\"RawClass\" IN ('ChipDg1','ChipDg2Portrait','ChipDg13','ChipDg15','ChipSod','AaChallenge','AaResponse','LiveSelfieImage','LivenessMedia','HandSignatureImage')");
                        });
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportDecisionEligibilityCauseRow", b =>
                {
                    b.Property<Guid>("ExportDecisionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<string>("Cause")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ExportDecisionId", "Ordinal")
                        .HasName("PK_raw_export_decision_eligibility_causes");

                    b.ToTable("raw_export_decision_eligibility_causes", "tagekyc", t =>
                        {
                            t.HasCheckConstraint("CK_raw_export_decision_eligibility_causes_Cause_enum", "\"Cause\" IN ('GrantMissing','GrantRevoked','PolicyNotActive','PolicyRevoked','PolicySuspended','NotCatalogApproved','StaleRuleSet','MissingOrInvalidFulfillment')");

                            t.HasCheckConstraint("CK_raw_export_decision_eligibility_causes_Ordinal_nonneg", "\"Ordinal\" >= 0");
                        });
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportDecisionFulfillmentRefRow", b =>
                {
                    b.Property<Guid>("ExportDecisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequirementType")
                        .HasColumnType("text");

                    b.Property<string>("ArtifactRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ArtifactVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FulfillmentEventId")
                        .HasColumnType("uuid");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ValidUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ExportDecisionId", "RequirementType")
                        .HasName("PK_raw_export_decision_fulfillment_refs");

                    b.HasAlternateKey("ExportDecisionId", "Ordinal")
                        .HasName("UQ_raw_export_decision_fulfillment_refs_Ordinal");

                    b.ToTable("raw_export_decision_fulfillment_refs", "tagekyc", t =>
                        {
                            t.HasCheckConstraint("CK_raw_export_decision_fulfillment_refs_Ordinal_nonneg", "\"Ordinal\" >= 0");

                            t.HasCheckConstraint("CK_raw_export_decision_fulfillment_refs_RequirementType_enum", "\"RequirementType\" IN ('LegalApproval','ConsentArtifact','Dpia','CrossBorderAssessment','RetentionSchedule')");

                            t.HasCheckConstraint("CK_raw_export_decision_fulfillment_refs_Revision_pos", "\"Revision\" >= 1");
                        });
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportFulfillmentRow", b =>
                {
                    b.Property<Guid>("FulfillmentEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArtifactRef")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ArtifactVersion")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FulfillmentDecisionRef")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid");

                    b.Property<int>("PolicyVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecordedByPrincipalId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequirementType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<int?>("SupersedesRevision")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetRevision")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ValidFromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ValidUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("FulfillmentEventId");

                    b.HasIndex("PolicyId", "PolicyVersion", "RequirementType", "Revision")
                        .IsUnique();

                    b.ToTable("raw_export_fulfillments", "tagekyc", t =>
                        {
                            t.HasCheckConstraint("CK_raw_export_fulfillments_DecisionRef_NotBlank", "btrim(\"FulfillmentDecisionRef\") <> ''");

                            t.HasCheckConstraint("CK_raw_export_fulfillments_EventShape", "(\r\n                    \"EventType\" = 'Accepted'\r\n                    AND \"ArtifactRef\" IS NOT NULL\r\n                    AND btrim(\"ArtifactRef\") <> ''\r\n                    AND \"ArtifactVersion\" IS NOT NULL\r\n                    AND btrim(\"ArtifactVersion\") <> ''\r\n                    AND \"ValidFromUtc\" IS NOT NULL\r\n                    AND \"TargetRevision\" IS NULL\r\n                ) OR (\r\n                    \"EventType\" = 'Withdrawn'\r\n                    AND \"TargetRevision\" IS NOT NULL\r\n                    AND \"ArtifactRef\" IS NULL\r\n                    AND \"ArtifactVersion\" IS NULL\r\n                    AND \"ValidFromUtc\" IS NULL\r\n                    AND \"ValidUntilUtc\" IS NULL\r\n                    AND \"SupersedesRevision\" IS NULL\r\n                )");

                            t.HasCheckConstraint("CK_raw_export_fulfillments_EventType", "\"EventType\" IN ('Accepted','Withdrawn')");

                            t.HasCheckConstraint("CK_raw_export_fulfillments_RequirementType", "\"RequirementType\" IN ('LegalApproval','Dpia','CrossBorderAssessment','RetentionSchedule')");

                            t.HasCheckConstraint("CK_raw_export_fulfillments_Validity", "\"ValidUntilUtc\" IS NULL OR \"ValidFromUtc\" IS NULL OR \"ValidUntilUtc\" > \"ValidFromUtc\"");
                        });
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportGrantRow", b =>
                {
                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid");

                    b.Property<int>("PolicyVersion")
                        .HasColumnType("integer");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ClientApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("DecisionRef")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecordedByPrincipalId")
                        .HasColumnType("uuid");

                    b.HasKey("PrincipalId", "PolicyId", "PolicyVersion", "Revision");

                    b.HasIndex("PolicyId", "PolicyVersion");

                    b.ToTable("raw_export_grants", "tagekyc", t =>
                        {
                            t.HasCheckConstraint("CK_raw_export_grants_DecisionRef_NotBlank", "btrim(\"DecisionRef\") <> ''");

                            t.HasCheckConstraint("CK_raw_export_grants_EventType", "\"EventType\" IN ('Granted','Revoked')");
                        });
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportPermitClassRow", b =>
                {
                    b.Property<Guid>("PermitId")
                        .HasColumnType("uuid");

                    b.Property<string>("RawClass")
                        .HasColumnType("text");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.HasKey("PermitId", "RawClass")
                        .HasName("PK_raw_export_permit_classes");

                    b.HasAlternateKey("PermitId", "Ordinal")
                        .HasName("UQ_raw_export_permit_classes_Ordinal");

                    b.ToTable("raw_export_permit_classes", "tagekyc", t =>
                        {
                            t.HasCheckConstraint("CK_raw_export_permit_classes_Ordinal_nonneg", "\"Ordinal\" >= 0");

                            t.HasCheckConstraint("CK_raw_export_permit_classes_RawClass_enum", "\"RawClass\" IN ('ChipDg1','ChipDg2Portrait','ChipDg13','ChipDg15','ChipSod','AaChallenge','AaResponse','LiveSelfieImage','LivenessMedia','HandSignatureImage')");
                        });
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportPolicyAllowedClassRow", b =>
                {
                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid");

                    b.Property<int>("PolicyVersion")
                        .HasColumnType("integer");

                    b.Property<string>("RawClass")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PolicyId", "PolicyVersion", "RawClass");

                    b.ToTable("raw_export_policy_allowed_classes", "tagekyc", t =>
                        {
                            t.HasCheckConstraint("CK_raw_export_policy_allowed_classes_RawClass", "\"RawClass\" IN ('ChipDg1','ChipDg2Portrait','ChipDg13','ChipDg15','ChipSod','AaChallenge','AaResponse','LiveSelfieImage','LivenessMedia','HandSignatureImage')");
                        });
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportPolicyClosureRow", b =>
                {
                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid");

                    b.Property<int>("PolicyVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClosedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ClosureType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DecisionRef")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("PolicyId", "PolicyVersion");

                    b.ToTable("raw_export_policy_closures", "tagekyc", t =>
                        {
                            t.HasCheckConstraint("CK_raw_export_policy_closures_ClosureType", "\"ClosureType\" IN ('CatalogApproved','Abandoned')");

                            t.HasCheckConstraint("CK_raw_export_policy_closures_DecisionRef_NotBlank", "btrim(\"DecisionRef\") <> ''");

                            t.HasCheckConstraint("CK_raw_export_policy_closures_Principal_NotBlank", "btrim(\"ClosedByPrincipalId\") <> ''");
                        });
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportPolicyLifecycleRow", b =>
                {
                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid");

                    b.Property<int>("PolicyVersion")
                        .HasColumnType("integer");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<string>("DecisionRef")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecordedByPrincipalId")
                        .HasColumnType("uuid");

                    b.HasKey("PolicyId", "PolicyVersion", "Revision");

                    b.ToTable("raw_export_policy_lifecycle", "tagekyc", t =>
                        {
                            t.HasCheckConstraint("CK_raw_export_policy_lifecycle_DecisionRef_NotBlank", "btrim(\"DecisionRef\") <> ''");

                            t.HasCheckConstraint("CK_raw_export_policy_lifecycle_EventType", "\"EventType\" IN ('Activated','Suspended','Revoked')");
                        });
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportPolicyRequirementRow", b =>
                {
                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid");

                    b.Property<int>("PolicyVersion")
                        .HasColumnType("integer");

                    b.Property<string>("RequirementType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PolicyId", "PolicyVersion", "RequirementType");

                    b.ToTable("raw_export_policy_requirements", "tagekyc", t =>
                        {
                            t.HasCheckConstraint("CK_raw_export_policy_requirements_RequirementType", "\"RequirementType\" IN ('LegalApproval','ConsentArtifact','Dpia','CrossBorderAssessment','RetentionSchedule')");
                        });
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportPolicyVersionRow", b =>
                {
                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid");

                    b.Property<int>("PolicyVersion")
                        .HasColumnType("integer");

                    b.Property<string>("ConsentRequirement")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ControllerEntityRef")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ControllerJurisdiction")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("ControllerRole")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("PermitTtlSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("ProcessingInfrastructureJurisdiction")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RecipientAssuranceRequirement")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RecipientCategory")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RecipientJurisdiction")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("RequirementRuleSetId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("RequirementRuleSetVersion")
                        .HasColumnType("integer");

                    b.Property<string>("RetentionProfileRef")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RetentionPurposeCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TransferLegalBasisCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TransferScenarioCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("PolicyId", "PolicyVersion");

                    b.HasIndex("RequirementRuleSetId", "RequirementRuleSetVersion");

                    b.ToTable("raw_export_policy_versions", "tagekyc", t =>
                        {
                            t.HasCheckConstraint("CK_raw_export_policy_versions_ConsentRequirement", "\"ConsentRequirement\" IN ('Required','NotRequired')");

                            t.HasCheckConstraint("CK_raw_export_policy_versions_Mode", "\"Mode\" IN ('ExternalExportOnlyNoRetain','EncryptedExportPacket','EncryptedRawVaultRetained')");

                            t.HasCheckConstraint("CK_raw_export_policy_versions_Retention", "(\r\n                    \"Mode\" = 'ExternalExportOnlyNoRetain' AND \"RetentionProfileRef\" IS NULL\r\n                ) OR (\r\n                    \"Mode\" IN ('EncryptedExportPacket','EncryptedRawVaultRetained') AND \"RetentionProfileRef\" IS NOT NULL\r\n                )");
                        });
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportRequirementRuleRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequirementType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RuleSelector")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RuleSetId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("RuleSetVersion")
                        .HasColumnType("integer");

                    b.Property<string>("SelectorOperand")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("RuleSetId", "RuleSetVersion");

                    b.ToTable("raw_export_requirement_rules", "tagekyc", t =>
                        {
                            t.HasCheckConstraint("CK_raw_export_requirement_rules_RequirementType", "\"RequirementType\" IN ('LegalApproval','ConsentArtifact','Dpia','CrossBorderAssessment','RetentionSchedule')");

                            t.HasCheckConstraint("CK_raw_export_requirement_rules_RuleSelector", "\"RuleSelector\" IN ('Always','ModeEquals','ConsentRequired','AnyJurisdictionForeign')");

                            t.HasCheckConstraint("CK_raw_export_requirement_rules_RuleSetId", "\"RuleSetId\" = 'RAW_EXPORT_REQUIREMENTS'");

                            t.HasCheckConstraint("CK_raw_export_requirement_rules_SelectorOperand", "(\r\n                    \"RuleSelector\" = 'ModeEquals' AND \"SelectorOperand\" IN ('ExternalExportOnlyNoRetain','EncryptedExportPacket','EncryptedRawVaultRetained')\r\n                ) OR (\r\n                    \"RuleSelector\" IN ('Always','ConsentRequired','AnyJurisdictionForeign') AND \"SelectorOperand\" IS NULL\r\n                )");
                        });
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportRequirementRuleSetRow", b =>
                {
                    b.Property<string>("RuleSetId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("RuleSetVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HomeJurisdictionCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("MigrationRef")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("RuleSetId", "RuleSetVersion");

                    b.ToTable("raw_export_requirement_rule_sets", "tagekyc", t =>
                        {
                            t.HasCheckConstraint("CK_raw_export_requirement_rule_sets_HomeJurisdictionCode", "\"HomeJurisdictionCode\" ~ '^[A-Z]{2}$'");

                            t.HasCheckConstraint("CK_raw_export_requirement_rule_sets_RuleSetId", "\"RuleSetId\" = 'RAW_EXPORT_REQUIREMENTS'");
                        });
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportSubjectConsentAuthorityRow", b =>
                {
                    b.Property<Guid>("AuthorityEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorityPrincipalId")
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ClientApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("DecisionRef")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecordedByPrincipalId")
                        .HasColumnType("uuid");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetRevision")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ValidFromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ValidUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AuthorityEventId");

                    b.HasIndex("AuthorityPrincipalId", "ClientApplicationId", "AuthorityType", "Revision")
                        .IsUnique();

                    b.ToTable("raw_export_subject_consent_authorities", "tagekyc", t =>
                        {
                            t.HasCheckConstraint("CK_raw_export_subject_consent_authorities_AuthorityType", "\"AuthorityType\" IN ('SubjectConsentRecorder','SubjectConsentWithdrawer')");

                            t.HasCheckConstraint("CK_raw_export_subject_consent_authorities_DecisionRef_NotBlank", "\"DecisionRef\" IS NULL OR btrim(\"DecisionRef\") <> ''");

                            t.HasCheckConstraint("CK_raw_export_subject_consent_authorities_EventShape", "(\r\n    \"EventType\" = 'Granted'\r\n    AND \"TargetRevision\" IS NULL\r\n    AND \"ValidFromUtc\" IS NOT NULL\r\n    AND (\"ValidUntilUtc\" IS NULL OR \"ValidUntilUtc\" > \"ValidFromUtc\")\r\n) OR (\r\n    \"EventType\" = 'Revoked'\r\n    AND \"TargetRevision\" IS NOT NULL\r\n    AND \"ValidFromUtc\" IS NULL\r\n    AND \"ValidUntilUtc\" IS NULL\r\n)");

                            t.HasCheckConstraint("CK_raw_export_subject_consent_authorities_EventType", "\"EventType\" IN ('Granted','Revoked')");
                        });
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportSubjectConsentClassRow", b =>
                {
                    b.Property<Guid>("SubjectConsentRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("RawClass")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SubjectConsentRecordId", "RawClass");

                    b.ToTable("raw_export_subject_consent_classes", "tagekyc", t =>
                        {
                            t.HasCheckConstraint("CK_raw_export_subject_consent_classes_RawClass", "\"RawClass\" IN ('ChipDg1','ChipDg2Portrait','ChipDg13','ChipDg15','ChipSod','AaChallenge','AaResponse','LiveSelfieImage','LivenessMedia','HandSignatureImage')");
                        });
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportSubjectConsentEventRow", b =>
                {
                    b.Property<Guid>("SubjectConsentRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CapturedByPrincipalId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("ConsentScopeHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ConsentTextContentHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ConsentTextVersion")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DecisionRef")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ExternalConsentArtifactRef")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid");

                    b.Property<int>("PolicyVersion")
                        .HasColumnType("integer");

                    b.Property<string>("PurposeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("RecipientClientApplicationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<string>("SubjectRef")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("TargetRevision")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ValidFromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ValidUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VerificationSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WithdrawnByPrincipalId")
                        .HasColumnType("uuid");

                    b.HasKey("SubjectConsentRecordId");

                    b.HasIndex("VerificationSessionId", "SubjectRef", "PolicyId", "PolicyVersion", "PurposeCode", "RecipientClientApplicationId", "Revision")
                        .IsUnique();

                    b.ToTable("raw_export_subject_consent_events", "tagekyc", t =>
                        {
                            t.HasCheckConstraint("CK_raw_export_subject_consent_events_EventShape", "(\r\n    \"EventType\" = 'Granted'\r\n    AND \"TargetRevision\" IS NULL\r\n    AND \"ConsentTextVersion\" IS NOT NULL AND btrim(\"ConsentTextVersion\") <> ''\r\n    AND \"ConsentTextContentHash\" IS NOT NULL AND btrim(\"ConsentTextContentHash\") <> ''\r\n    AND \"ExternalConsentArtifactRef\" IS NOT NULL AND btrim(\"ExternalConsentArtifactRef\") <> ''\r\n    AND (\"DecisionRef\" IS NULL OR btrim(\"DecisionRef\") <> '')\r\n    AND \"ValidFromUtc\" IS NOT NULL\r\n    AND \"CapturedAtUtc\" IS NOT NULL\r\n    AND \"CapturedByPrincipalId\" IS NOT NULL\r\n    AND \"WithdrawnByPrincipalId\" IS NULL\r\n    AND (\"ValidUntilUtc\" IS NULL OR \"ValidUntilUtc\" > \"ValidFromUtc\")\r\n) OR (\r\n    \"EventType\" = 'Withdrawn'\r\n    AND \"TargetRevision\" IS NOT NULL\r\n    AND \"ConsentTextVersion\" IS NULL\r\n    AND \"ConsentTextContentHash\" IS NULL\r\n    AND \"ValidFromUtc\" IS NULL\r\n    AND \"ValidUntilUtc\" IS NULL\r\n    AND \"CapturedAtUtc\" IS NULL\r\n    AND \"CapturedByPrincipalId\" IS NULL\r\n    AND \"WithdrawnByPrincipalId\" IS NOT NULL\r\n)");

                            t.HasCheckConstraint("CK_raw_export_subject_consent_events_EventType", "\"EventType\" IN ('Granted','Withdrawn')");

                            t.HasCheckConstraint("CK_raw_export_subject_consent_events_HashLength", "octet_length(\"ConsentScopeHash\") = 32");

                            t.HasCheckConstraint("CK_raw_export_subject_consent_events_PurposeCode", "\"PurposeCode\" = 'SubjectRawBiometricExport'");
                        });
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.VerificationDecisionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssuranceLevel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CompletedChecksJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecisionReasonCodesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("FailedChecksJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RetryReasonCodesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<decimal?>("RiskScore")
                        .HasColumnType("numeric");

                    b.Property<Guid>("VerificationSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VerificationSessionId");

                    b.ToTable("verification_decisions", "tagekyc");
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.VerificationSessionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AccessAuditRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("ActorCategory")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ActorId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("AssuranceLevel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("BindingNonceHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("ClientApplicationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletionEligibility")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("EvidencePackageHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("EvidencePackageId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalSessionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ExternalTransactionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("FinalDecisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("LegalHoldStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ManifestHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PolicySnapshotId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PurgeBlockReason")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RequiredChecksJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RetentionClass")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SubjectRef")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ClientApplicationId", "ExternalSessionId")
                        .IsUnique()
                        .HasFilter("\"ExternalSessionId\" IS NOT NULL");

                    b.ToTable("verification_sessions", "tagekyc");
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.AppendIdempotencyRecordRow", b =>
                {
                    b.HasOne("TagEkyc.Infrastructure.Persistence.Entities.VerificationSessionRow", null)
                        .WithMany()
                        .HasForeignKey("VerificationSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.AuditEventRow", b =>
                {
                    b.HasOne("TagEkyc.Infrastructure.Persistence.Entities.VerificationSessionRow", null)
                        .WithMany()
                        .HasForeignKey("VerificationSessionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.CaptureArtifactRow", b =>
                {
                    b.HasOne("TagEkyc.Infrastructure.Persistence.Entities.VerificationSessionRow", null)
                        .WithMany()
                        .HasForeignKey("VerificationSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.EvidenceManifestRow", b =>
                {
                    b.HasOne("TagEkyc.Infrastructure.Persistence.Entities.EvidencePackageRow", null)
                        .WithOne()
                        .HasForeignKey("TagEkyc.Infrastructure.Persistence.Entities.EvidenceManifestRow", "EvidencePackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.EvidencePackageRow", b =>
                {
                    b.HasOne("TagEkyc.Infrastructure.Persistence.Entities.VerificationSessionRow", null)
                        .WithMany()
                        .HasForeignKey("VerificationSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.EvidenceResultRow", b =>
                {
                    b.HasOne("TagEkyc.Infrastructure.Persistence.Entities.VerificationSessionRow", null)
                        .WithMany()
                        .HasForeignKey("VerificationSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportAuthorizationDecisionRow", b =>
                {
                    b.HasOne("TagEkyc.Infrastructure.Persistence.Entities.VerificationSessionRow", null)
                        .WithMany()
                        .HasForeignKey("ResolvedVerificationSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_raw_export_authorization_decisions_session");
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportAuthorizationIdempotencyRow", b =>
                {
                    b.HasOne("TagEkyc.Infrastructure.Persistence.Entities.RawExportAuthorizationDecisionRow", null)
                        .WithMany()
                        .HasForeignKey("ExportDecisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_raw_export_authorization_idempotency_decision");
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportAuthorizationPermitRow", b =>
                {
                    b.HasOne("TagEkyc.Infrastructure.Persistence.Entities.RawExportAuthorizationDecisionRow", null)
                        .WithMany()
                        .HasForeignKey("AuthorizationDecisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_raw_export_authorization_permits_decision");

                    b.HasOne("TagEkyc.Infrastructure.Persistence.Entities.VerificationSessionRow", null)
                        .WithMany()
                        .HasForeignKey("ResolvedVerificationSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_raw_export_authorization_permits_session");
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportDecisionClassRow", b =>
                {
                    b.HasOne("TagEkyc.Infrastructure.Persistence.Entities.RawExportAuthorizationDecisionRow", null)
                        .WithMany()
                        .HasForeignKey("ExportDecisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_raw_export_decision_classes_decision");
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportDecisionEligibilityCauseRow", b =>
                {
                    b.HasOne("TagEkyc.Infrastructure.Persistence.Entities.RawExportAuthorizationDecisionRow", null)
                        .WithMany()
                        .HasForeignKey("ExportDecisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_raw_export_decision_eligibility_causes_decision");
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportDecisionFulfillmentRefRow", b =>
                {
                    b.HasOne("TagEkyc.Infrastructure.Persistence.Entities.RawExportAuthorizationDecisionRow", null)
                        .WithMany()
                        .HasForeignKey("ExportDecisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_raw_export_decision_fulfillment_refs_decision");
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportFulfillmentRow", b =>
                {
                    b.HasOne("TagEkyc.Infrastructure.Persistence.Entities.RawExportPolicyVersionRow", null)
                        .WithMany()
                        .HasForeignKey("PolicyId", "PolicyVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportGrantRow", b =>
                {
                    b.HasOne("TagEkyc.Infrastructure.Persistence.Entities.RawExportPolicyVersionRow", null)
                        .WithMany()
                        .HasForeignKey("PolicyId", "PolicyVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportPermitClassRow", b =>
                {
                    b.HasOne("TagEkyc.Infrastructure.Persistence.Entities.RawExportAuthorizationPermitRow", null)
                        .WithMany()
                        .HasForeignKey("PermitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_raw_export_permit_classes_permit");
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportPolicyAllowedClassRow", b =>
                {
                    b.HasOne("TagEkyc.Infrastructure.Persistence.Entities.RawExportPolicyVersionRow", null)
                        .WithMany()
                        .HasForeignKey("PolicyId", "PolicyVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportPolicyClosureRow", b =>
                {
                    b.HasOne("TagEkyc.Infrastructure.Persistence.Entities.RawExportPolicyVersionRow", null)
                        .WithOne()
                        .HasForeignKey("TagEkyc.Infrastructure.Persistence.Entities.RawExportPolicyClosureRow", "PolicyId", "PolicyVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportPolicyLifecycleRow", b =>
                {
                    b.HasOne("TagEkyc.Infrastructure.Persistence.Entities.RawExportPolicyVersionRow", null)
                        .WithMany()
                        .HasForeignKey("PolicyId", "PolicyVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportPolicyRequirementRow", b =>
                {
                    b.HasOne("TagEkyc.Infrastructure.Persistence.Entities.RawExportPolicyVersionRow", null)
                        .WithMany()
                        .HasForeignKey("PolicyId", "PolicyVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportPolicyVersionRow", b =>
                {
                    b.HasOne("TagEkyc.Infrastructure.Persistence.Entities.RawExportRequirementRuleSetRow", null)
                        .WithMany()
                        .HasForeignKey("RequirementRuleSetId", "RequirementRuleSetVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportRequirementRuleRow", b =>
                {
                    b.HasOne("TagEkyc.Infrastructure.Persistence.Entities.RawExportRequirementRuleSetRow", null)
                        .WithMany()
                        .HasForeignKey("RuleSetId", "RuleSetVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.RawExportSubjectConsentClassRow", b =>
                {
                    b.HasOne("TagEkyc.Infrastructure.Persistence.Entities.RawExportSubjectConsentEventRow", null)
                        .WithMany()
                        .HasForeignKey("SubjectConsentRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TagEkyc.Infrastructure.Persistence.Entities.VerificationDecisionRow", b =>
                {
                    b.HasOne("TagEkyc.Infrastructure.Persistence.Entities.VerificationSessionRow", null)
                        .WithMany()
                        .HasForeignKey("VerificationSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
